import Head from 'next/head';
import { testAtom } from '../atoms/testAtom';
import { useRecoilState, useRecoilValue, useSetRecoilState } from 'recoil';
import { useRef } from 'react';

export default function Home() {
  const valuesFromAtom = useRecoilValue(testAtom); //zoberie value
  const setValueToAtom = useSetRecoilState(testAtom); // nastavi value
  const [testValue, setTestValue] = useRecoilState(testAtom); // state value
  const idValue = useRef();

  const setValue = (e) => {
    e.preventDefault();
    const id = valuesFromAtom.length + 1;
    const res = testValue.map((item) => item.amount);
    console.log(res);
    setValueToAtom((prev) => [
      ...prev,
      {
        id: id,
        amount: 1000,
        text: 'Another stuff',
      },
    ]);
  };
  const deleteById = (e) => {
    e.preventDefault();
    const index = testValue.findIndex((item) => item.id === +idValue.current.value);
    index !== -1
      ? setTestValue([...testValue.slice(0, index), ...testValue.slice(index + 1)])
      : console.log('id not found');
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div className="flex flex-col justify-center w-full space-y-2">
          {valuesFromAtom.map((item, key) => (
            <div key={key}>
              <p>{item.id}</p>
              <p>{item.amount}</p>
              <p>{item.text}</p>
            </div>
          ))}
        </div>
        <div className="mt-10">
          <button onClick={setValue} className="border">
            Nastav value do Atomu
          </button>
        </div>
      </section>
      <section>
        <div className="flex flex-col justify-center w-full space-y-2">
          {testValue.map((item, key) => (
            <div key={key}>
              <p>{item.id}</p>
              <p>{item.amount}</p>
              <p>{item.text}</p>
            </div>
          ))}
        </div>
        <div className="mt-10">
          <input type="number" className="border" ref={idValue} />
          <button onClick={deleteById} className="border">
            Delete id
          </button>
        </div>
      </section>
    </div>
  );
}
